### ISSUE TITLE
[Help] attaching images inline body using --attach-body

### ISSUE THREAD

**Issue by redcat42** [jetmore/swaks#79] opened 2023-12-24 07:48 UTC
.

**Comment by jetmore** [comment] 2024-01-07 20:08
Swaks can't do this.  I'll keep this ticket open in case I ever get into serious MIME mangling, but I don't really anticipate doing this

**Comment by redcat42** [comment] 2024-01-08 03:53
thanks for replying

the hope is to attach images to an email and view them inline as opposed to creating a html with urls as most email providers are unnecessarily scanning emails for links with the pretext of checking for malware or phishing emails whilst collecting metadata on links sent, from the privacy perspective i requested to see if it was possible

i understand if the feature is not implemented tho, might be a pain to get it going 

happy new year :)

**Comment by jetmore** [comment] 2024-03-05 20:02
closing since the original author removed the body of their query

**Closed by jetmore** 2024-03-05 20:02 UTC

**Comment by calumk** [comment] 2024-04-05 06:42
Hi @jetmore 

Does this mean you can't currently send an email with an image embeded in it? 

I am using swaks to assist in developing a helpdesk package, and so sometimes users will have images in the body of their email, or company logos etc in the footer of their emails. 

Is there a way to emulate this? 

Cheers,

---

For Reference - The original question asked by redcat was : 

>   I saw this
>   
>   `swaks --attach-type text/html --attach-body @report.html`
>   
>   here https://www.jetmore.org/john/code/swaks/faq.html
>   
>   was curious if it is possible to attach images inline in body of the email.
>   
>   `--attach` works fine to attach the images as an attachment, inline would be neat, if possible.

**Comment by jetmore** [comment] 2024-07-27 19:27
@calumk there's nothing technically impossible about sending any message type, the problem is who is responsible for building the message.  If you build the message you want outside of swaks, you can just used --data to send it verbatim.  But swaks has fairly minimal MIME tooling and doesn't currently know anything about inline images.  Something could probably be added if someone sent me something like "with a command line like this, I'd like to see a resulting SMTP data section that looks like this".  Probably in a different ticket than this one
